// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mini_room.proto

package com.yanchuanli.games.pokr.model;

public final class MiniRoomProtos {
  private MiniRoomProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MiniRoomOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated .com.yanchuanli.games.pokr.model.MiniPlayer mini_players = 3;
    java.util.List<com.yanchuanli.games.pokr.model.MiniPlayerProtos.MiniPlayer> 
        getMiniPlayersList();
    com.yanchuanli.games.pokr.model.MiniPlayerProtos.MiniPlayer getMiniPlayers(int index);
    int getMiniPlayersCount();
    java.util.List<? extends com.yanchuanli.games.pokr.model.MiniPlayerProtos.MiniPlayerOrBuilder> 
        getMiniPlayersOrBuilderList();
    com.yanchuanli.games.pokr.model.MiniPlayerProtos.MiniPlayerOrBuilder getMiniPlayersOrBuilder(
        int index);
    
    // required string name = 2;
    boolean hasName();
    String getName();
    
    // required string id = 1;
    boolean hasId();
    String getId();
  }
  public static final class MiniRoom extends
      com.google.protobuf.GeneratedMessage
      implements MiniRoomOrBuilder {
    // Use MiniRoom.newBuilder() to construct.
    private MiniRoom(Builder builder) {
      super(builder);
    }
    private MiniRoom(boolean noInit) {}
    
    private static final MiniRoom defaultInstance;
    public static MiniRoom getDefaultInstance() {
      return defaultInstance;
    }
    
    public MiniRoom getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yanchuanli.games.pokr.model.MiniRoomProtos.internal_static_com_yanchuanli_games_pokr_model_MiniRoom_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yanchuanli.games.pokr.model.MiniRoomProtos.internal_static_com_yanchuanli_games_pokr_model_MiniRoom_fieldAccessorTable;
    }
    
    private int bitField0_;
    // repeated .com.yanchuanli.games.pokr.model.MiniPlayer mini_players = 3;
    public static final int MINI_PLAYERS_FIELD_NUMBER = 3;
    private java.util.List<com.yanchuanli.games.pokr.model.MiniPlayerProtos.MiniPlayer> miniPlayers_;
    public java.util.List<com.yanchuanli.games.pokr.model.MiniPlayerProtos.MiniPlayer> getMiniPlayersList() {
      return miniPlayers_;
    }
    public java.util.List<? extends com.yanchuanli.games.pokr.model.MiniPlayerProtos.MiniPlayerOrBuilder> 
        getMiniPlayersOrBuilderList() {
      return miniPlayers_;
    }
    public int getMiniPlayersCount() {
      return miniPlayers_.size();
    }
    public com.yanchuanli.games.pokr.model.MiniPlayerProtos.MiniPlayer getMiniPlayers(int index) {
      return miniPlayers_.get(index);
    }
    public com.yanchuanli.games.pokr.model.MiniPlayerProtos.MiniPlayerOrBuilder getMiniPlayersOrBuilder(
        int index) {
      return miniPlayers_.get(index);
    }
    
    // required string name = 2;
    public static final int NAME_FIELD_NUMBER = 2;
    private java.lang.Object name_;
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          name_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private java.lang.Object id_;
    public boolean hasId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          id_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      miniPlayers_ = java.util.Collections.emptyList();
      name_ = "";
      id_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getMiniPlayersCount(); i++) {
        if (!getMiniPlayers(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(2, getNameBytes());
      }
      for (int i = 0; i < miniPlayers_.size(); i++) {
        output.writeMessage(3, miniPlayers_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getNameBytes());
      }
      for (int i = 0; i < miniPlayers_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, miniPlayers_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.yanchuanli.games.pokr.model.MiniRoomProtos.MiniRoom parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.yanchuanli.games.pokr.model.MiniRoomProtos.MiniRoom parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.yanchuanli.games.pokr.model.MiniRoomProtos.MiniRoom parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.yanchuanli.games.pokr.model.MiniRoomProtos.MiniRoom parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.yanchuanli.games.pokr.model.MiniRoomProtos.MiniRoom parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.yanchuanli.games.pokr.model.MiniRoomProtos.MiniRoom parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.yanchuanli.games.pokr.model.MiniRoomProtos.MiniRoom parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.yanchuanli.games.pokr.model.MiniRoomProtos.MiniRoom parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.yanchuanli.games.pokr.model.MiniRoomProtos.MiniRoom parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.yanchuanli.games.pokr.model.MiniRoomProtos.MiniRoom parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.yanchuanli.games.pokr.model.MiniRoomProtos.MiniRoom prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.yanchuanli.games.pokr.model.MiniRoomProtos.MiniRoomOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.yanchuanli.games.pokr.model.MiniRoomProtos.internal_static_com_yanchuanli_games_pokr_model_MiniRoom_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.yanchuanli.games.pokr.model.MiniRoomProtos.internal_static_com_yanchuanli_games_pokr_model_MiniRoom_fieldAccessorTable;
      }
      
      // Construct using com.yanchuanli.games.pokr.model.MiniRoomProtos.MiniRoom.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getMiniPlayersFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (miniPlayersBuilder_ == null) {
          miniPlayers_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          miniPlayersBuilder_.clear();
        }
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        id_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.yanchuanli.games.pokr.model.MiniRoomProtos.MiniRoom.getDescriptor();
      }
      
      public com.yanchuanli.games.pokr.model.MiniRoomProtos.MiniRoom getDefaultInstanceForType() {
        return com.yanchuanli.games.pokr.model.MiniRoomProtos.MiniRoom.getDefaultInstance();
      }
      
      public com.yanchuanli.games.pokr.model.MiniRoomProtos.MiniRoom build() {
        com.yanchuanli.games.pokr.model.MiniRoomProtos.MiniRoom result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.yanchuanli.games.pokr.model.MiniRoomProtos.MiniRoom buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.yanchuanli.games.pokr.model.MiniRoomProtos.MiniRoom result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.yanchuanli.games.pokr.model.MiniRoomProtos.MiniRoom buildPartial() {
        com.yanchuanli.games.pokr.model.MiniRoomProtos.MiniRoom result = new com.yanchuanli.games.pokr.model.MiniRoomProtos.MiniRoom(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (miniPlayersBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            miniPlayers_ = java.util.Collections.unmodifiableList(miniPlayers_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.miniPlayers_ = miniPlayers_;
        } else {
          result.miniPlayers_ = miniPlayersBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000002;
        }
        result.id_ = id_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.yanchuanli.games.pokr.model.MiniRoomProtos.MiniRoom) {
          return mergeFrom((com.yanchuanli.games.pokr.model.MiniRoomProtos.MiniRoom)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.yanchuanli.games.pokr.model.MiniRoomProtos.MiniRoom other) {
        if (other == com.yanchuanli.games.pokr.model.MiniRoomProtos.MiniRoom.getDefaultInstance()) return this;
        if (miniPlayersBuilder_ == null) {
          if (!other.miniPlayers_.isEmpty()) {
            if (miniPlayers_.isEmpty()) {
              miniPlayers_ = other.miniPlayers_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureMiniPlayersIsMutable();
              miniPlayers_.addAll(other.miniPlayers_);
            }
            onChanged();
          }
        } else {
          if (!other.miniPlayers_.isEmpty()) {
            if (miniPlayersBuilder_.isEmpty()) {
              miniPlayersBuilder_.dispose();
              miniPlayersBuilder_ = null;
              miniPlayers_ = other.miniPlayers_;
              bitField0_ = (bitField0_ & ~0x00000001);
              miniPlayersBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getMiniPlayersFieldBuilder() : null;
            } else {
              miniPlayersBuilder_.addAllMessages(other.miniPlayers_);
            }
          }
        }
        if (other.hasName()) {
          setName(other.getName());
        }
        if (other.hasId()) {
          setId(other.getId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasName()) {
          
          return false;
        }
        if (!hasId()) {
          
          return false;
        }
        for (int i = 0; i < getMiniPlayersCount(); i++) {
          if (!getMiniPlayers(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000004;
              id_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              name_ = input.readBytes();
              break;
            }
            case 26: {
              com.yanchuanli.games.pokr.model.MiniPlayerProtos.MiniPlayer.Builder subBuilder = com.yanchuanli.games.pokr.model.MiniPlayerProtos.MiniPlayer.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addMiniPlayers(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated .com.yanchuanli.games.pokr.model.MiniPlayer mini_players = 3;
      private java.util.List<com.yanchuanli.games.pokr.model.MiniPlayerProtos.MiniPlayer> miniPlayers_ =
        java.util.Collections.emptyList();
      private void ensureMiniPlayersIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          miniPlayers_ = new java.util.ArrayList<com.yanchuanli.games.pokr.model.MiniPlayerProtos.MiniPlayer>(miniPlayers_);
          bitField0_ |= 0x00000001;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          com.yanchuanli.games.pokr.model.MiniPlayerProtos.MiniPlayer, com.yanchuanli.games.pokr.model.MiniPlayerProtos.MiniPlayer.Builder, com.yanchuanli.games.pokr.model.MiniPlayerProtos.MiniPlayerOrBuilder> miniPlayersBuilder_;
      
      public java.util.List<com.yanchuanli.games.pokr.model.MiniPlayerProtos.MiniPlayer> getMiniPlayersList() {
        if (miniPlayersBuilder_ == null) {
          return java.util.Collections.unmodifiableList(miniPlayers_);
        } else {
          return miniPlayersBuilder_.getMessageList();
        }
      }
      public int getMiniPlayersCount() {
        if (miniPlayersBuilder_ == null) {
          return miniPlayers_.size();
        } else {
          return miniPlayersBuilder_.getCount();
        }
      }
      public com.yanchuanli.games.pokr.model.MiniPlayerProtos.MiniPlayer getMiniPlayers(int index) {
        if (miniPlayersBuilder_ == null) {
          return miniPlayers_.get(index);
        } else {
          return miniPlayersBuilder_.getMessage(index);
        }
      }
      public Builder setMiniPlayers(
          int index, com.yanchuanli.games.pokr.model.MiniPlayerProtos.MiniPlayer value) {
        if (miniPlayersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMiniPlayersIsMutable();
          miniPlayers_.set(index, value);
          onChanged();
        } else {
          miniPlayersBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setMiniPlayers(
          int index, com.yanchuanli.games.pokr.model.MiniPlayerProtos.MiniPlayer.Builder builderForValue) {
        if (miniPlayersBuilder_ == null) {
          ensureMiniPlayersIsMutable();
          miniPlayers_.set(index, builderForValue.build());
          onChanged();
        } else {
          miniPlayersBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addMiniPlayers(com.yanchuanli.games.pokr.model.MiniPlayerProtos.MiniPlayer value) {
        if (miniPlayersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMiniPlayersIsMutable();
          miniPlayers_.add(value);
          onChanged();
        } else {
          miniPlayersBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addMiniPlayers(
          int index, com.yanchuanli.games.pokr.model.MiniPlayerProtos.MiniPlayer value) {
        if (miniPlayersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMiniPlayersIsMutable();
          miniPlayers_.add(index, value);
          onChanged();
        } else {
          miniPlayersBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addMiniPlayers(
          com.yanchuanli.games.pokr.model.MiniPlayerProtos.MiniPlayer.Builder builderForValue) {
        if (miniPlayersBuilder_ == null) {
          ensureMiniPlayersIsMutable();
          miniPlayers_.add(builderForValue.build());
          onChanged();
        } else {
          miniPlayersBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addMiniPlayers(
          int index, com.yanchuanli.games.pokr.model.MiniPlayerProtos.MiniPlayer.Builder builderForValue) {
        if (miniPlayersBuilder_ == null) {
          ensureMiniPlayersIsMutable();
          miniPlayers_.add(index, builderForValue.build());
          onChanged();
        } else {
          miniPlayersBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllMiniPlayers(
          java.lang.Iterable<? extends com.yanchuanli.games.pokr.model.MiniPlayerProtos.MiniPlayer> values) {
        if (miniPlayersBuilder_ == null) {
          ensureMiniPlayersIsMutable();
          super.addAll(values, miniPlayers_);
          onChanged();
        } else {
          miniPlayersBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearMiniPlayers() {
        if (miniPlayersBuilder_ == null) {
          miniPlayers_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          miniPlayersBuilder_.clear();
        }
        return this;
      }
      public Builder removeMiniPlayers(int index) {
        if (miniPlayersBuilder_ == null) {
          ensureMiniPlayersIsMutable();
          miniPlayers_.remove(index);
          onChanged();
        } else {
          miniPlayersBuilder_.remove(index);
        }
        return this;
      }
      public com.yanchuanli.games.pokr.model.MiniPlayerProtos.MiniPlayer.Builder getMiniPlayersBuilder(
          int index) {
        return getMiniPlayersFieldBuilder().getBuilder(index);
      }
      public com.yanchuanli.games.pokr.model.MiniPlayerProtos.MiniPlayerOrBuilder getMiniPlayersOrBuilder(
          int index) {
        if (miniPlayersBuilder_ == null) {
          return miniPlayers_.get(index);  } else {
          return miniPlayersBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends com.yanchuanli.games.pokr.model.MiniPlayerProtos.MiniPlayerOrBuilder> 
           getMiniPlayersOrBuilderList() {
        if (miniPlayersBuilder_ != null) {
          return miniPlayersBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(miniPlayers_);
        }
      }
      public com.yanchuanli.games.pokr.model.MiniPlayerProtos.MiniPlayer.Builder addMiniPlayersBuilder() {
        return getMiniPlayersFieldBuilder().addBuilder(
            com.yanchuanli.games.pokr.model.MiniPlayerProtos.MiniPlayer.getDefaultInstance());
      }
      public com.yanchuanli.games.pokr.model.MiniPlayerProtos.MiniPlayer.Builder addMiniPlayersBuilder(
          int index) {
        return getMiniPlayersFieldBuilder().addBuilder(
            index, com.yanchuanli.games.pokr.model.MiniPlayerProtos.MiniPlayer.getDefaultInstance());
      }
      public java.util.List<com.yanchuanli.games.pokr.model.MiniPlayerProtos.MiniPlayer.Builder> 
           getMiniPlayersBuilderList() {
        return getMiniPlayersFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.yanchuanli.games.pokr.model.MiniPlayerProtos.MiniPlayer, com.yanchuanli.games.pokr.model.MiniPlayerProtos.MiniPlayer.Builder, com.yanchuanli.games.pokr.model.MiniPlayerProtos.MiniPlayerOrBuilder> 
          getMiniPlayersFieldBuilder() {
        if (miniPlayersBuilder_ == null) {
          miniPlayersBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.yanchuanli.games.pokr.model.MiniPlayerProtos.MiniPlayer, com.yanchuanli.games.pokr.model.MiniPlayerProtos.MiniPlayer.Builder, com.yanchuanli.games.pokr.model.MiniPlayerProtos.MiniPlayerOrBuilder>(
                  miniPlayers_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          miniPlayers_ = null;
        }
        return miniPlayersBuilder_;
      }
      
      // required string name = 2;
      private java.lang.Object name_ = "";
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      void setName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
      }
      
      // required string id = 1;
      private java.lang.Object id_ = "";
      public boolean hasId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        id_ = value;
        onChanged();
        return this;
      }
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      void setId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        id_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:com.yanchuanli.games.pokr.model.MiniRoom)
    }
    
    static {
      defaultInstance = new MiniRoom(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.yanchuanli.games.pokr.model.MiniRoom)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_yanchuanli_games_pokr_model_MiniRoom_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_yanchuanli_games_pokr_model_MiniRoom_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017mini_room.proto\022\037com.yanchuanli.games." +
      "pokr.model\032\021mini_player.proto\"g\n\010MiniRoo" +
      "m\022A\n\014mini_players\030\003 \003(\0132+.com.yanchuanli" +
      ".games.pokr.model.MiniPlayer\022\014\n\004name\030\002 \002" +
      "(\t\022\n\n\002id\030\001 \002(\tB1\n\037com.yanchuanli.games.p" +
      "okr.modelB\016MiniRoomProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_yanchuanli_games_pokr_model_MiniRoom_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_yanchuanli_games_pokr_model_MiniRoom_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_yanchuanli_games_pokr_model_MiniRoom_descriptor,
              new java.lang.String[] { "MiniPlayers", "Name", "Id", },
              com.yanchuanli.games.pokr.model.MiniRoomProtos.MiniRoom.class,
              com.yanchuanli.games.pokr.model.MiniRoomProtos.MiniRoom.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.yanchuanli.games.pokr.model.MiniPlayerProtos.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
